""" The file where all Astro types get defined. """

__author__  = 'xyLotus, bellrise'
__version__ = '0.1'


class TokenType:
    """ Basically an enum of all token types. """
    
    SPACE   = 0  # ' '      (1 space) 
    SYM     = 1  # [symbol] (alphanumerical)
    EXCL    = 2  # !

    LPAREN  = 3  # (
    RPAREN  = 4  # )
    LBRACK  = 5  # [
    RBRACK  = 6  # ]
    LBRACE  = 7  # {
    RBRACE  = 8  # }
    LCHEV   = 9  # <
    RCHEV   = 10 # >

    COMMA   = 11 # ,
    COLON   = 12 # :

    NAME    = 13 # [string_name] (alphanumerical)
    TAB     = 14 # '    '        (4 spaces)
    NEWLINE = 15 # \n

class Token:
    """This class represents a single Token which can then be put into a list
    generated by the Tokenizer. """

    def __init__(self, id_=TokenType.NONE, value=''):
        self.id = id_
        self.value = value

    def __str__(self):
        """Generate a string representation of the Token using some reflective
        Python magic. """

        str_token = '?'
        for name, value in TokenType.__dict__.items():
            if value == self.id:
                str_token = name
        return f'<Token id={str_token} value=\'{self.value}\'>'
