/**
 * Astro Virtual Machine
 *
 * Copyright (C) 2021 bellrise
 *
 * This file is licenced under the GNU Public Licence v3.0 which can be found
 * at the root of this project found at <https://github.com/xyLotus/Astro>.
 */
#ifndef AVM_BC_H_
#define AVM_BC_H_

/* This file provides types and definitions for operating on Astro bytecode
   generated by the compiler. */

typedef unsigned char   _bc8;
typedef unsigned short  _bc16;
typedef unsigned int    _bc32;
typedef unsigned int    _bc_ptr;

#define BC_VERSION  1
#define BC_MAGIC    "\x5aABC"

/* Bytecode header. This is located at the beginning of every compiled bytecode
   file containing useful meta information about the file. The strings with
   names are located after the header with null bytes in between, in the exact
   order the lengths are provided in the header. */
struct __attribute__((packed)) bc_hdr
{
    _bc8    hdr_magic[4];       /* magic bytes */
    _bc32   hdr_version;        /* version */
    _bc32   hdr_size;           /* sizeof bc_hdr + sizeof hdr_data */
    _bc32   hdr_flags;          /* header flags */
    _bc8    hdr_sys;            /* system */
    _bc8    hdr_endian;         /* file endianness */
    _bc_ptr hdr_off_data;       /* data segment */
    _bc_ptr hdr_off_code;       /* code segment */
    _bc_ptr hdr_off_mut;        /* mutable data segment */
    _bc_ptr hdr_off_oname;      /* source name */
    _bc_ptr hdr_off_mname;      /* module name */
    _bc_ptr hdr_off_func;       /* main function name */
};

/* Single instruction */

struct bc_ins
{
    _bc16   ins_type;           /* type of instruction */
    _bc16   ins_len;            /* payload length */
    _bc_ptr ins_source;         /* pointer to source string */
    _bc8    ins_payload[];      /* payload */
};

/* Symbol, also known as a function. sym_ptr points to the start of the
   BCO_FUNCTION instruction. */

struct bc_sym
{
    _bc_ptr sym_pos;            /* location of symbol in file */
    _bc16   sym_len;            /* length of symbol */
    _bc16   sym_flags;          /* symbol flags */
    _bc8    *sym_ptr;           /* pointer to symbol */
};

/* Every instruction (with debug symbols) should point to a bc_source structure
   somewhere in the data segment, which in turn provides information about the
   line number and contents of a line from the original source code. */

struct bc_source
{
    _bc32   src_line;           /* line of the source */
    _bc8    src_data[];         /* the actual string */
};

/* Universal values */

#define BC_FALSE            0x00
#define BC_TRUE             0x01

/* hdr_sys */

#define BC_SYS_UNKNOWN      0x00
#define BC_SYS_LINUX        0x01
#define BC_SYS_WIN          0x02

/* hdr_endian */

#define BC_ENDIAN_SMALL     0x00
#define BC_ENDIAN_BIG       0x01

/* hdr_flags */

#define BCF_HDR_BUILTIN     0x00000001      /* builtin module */
#define BCF_HDR_STANDALONE  0x00000002      /* no dependencies */

/* sym_flags */

#define BCF_SYM_PUBLIC      0x0001  /* public function */
#define BCF_SYM_PRIVATE     0x0002  /* private function */
#define BCF_SYM_METHOD      0x0004  /* method */
#define BCF_SYM_CALLED      0x0008  /* function was called */

/* ins_type */

#define BCO_NOP             0x0000  /* no operation */
                                    /* implementation-specific */
#define BCO_FUNCTION        0x0010  /* function definition */
#define BCO_ENDFUNC         0x0011  /* end of function definition */
#define BCO_BASECALL        0x0012  /* basic instruction call */
#define BCO_CALL            0x0013  /* function call */
#define BCO_IMPORT          0x0014  /* module import */
#define BCO_CREATE          0x0015  /* create variable */
#define BCO_ASSIGN          0x0016  /* assign to variable */
#define BCO_RETURN          0x0017  /* return */
#define BCO_IF              0x0018  /* if */
#define BCO_ELIF            0x0019  /* elif */
#define BCO_ELSE            0x001a  /* else */
#define BCO_ENDIF           0x001b  /* end of if statement */


#endif /* AVM_BC_H_ */
